export const fallbackCars = [
  {
    car_id: 1,
    name: "VinFast VF 9",
    brand: "VinFast",
    image_url:
      "/image/car/vf9.webp",
    price_per_day: 1800000,
    status: "available",
    color: "Green",
    seats: 7,
    fuel_type: "E-SUV",
    transmission: "Tự động",
    year: 2025,
    description: "Xe SUV cao cấp, hành trình dài, phù hợp gia đình và du lịch.",
  },
  {
    car_id: 2,
    name: "VinFast VF 3",
    brand: "VinFast",
    image_url:
      "/image/car/vf3.webp",
    price_per_day: 850000,
    status: "available",
    color: "Yellow",
    seats: 4,
    fuel_type: "Minicar",
    transmission: "Tự động",
    year: 2025,
    description: "Xe đô thị nhỏ gọn, linh hoạt, dễ lái trong phố.",
  },
  {
    car_id: 3,
    name: "VinFast VF 6",
    brand: "VinFast",
    image_url:
      "/image/car/vf6.webp",
    price_per_day: 1250000,
    status: "available",
    color: "Blue",
    seats: 5,
    fuel_type: "B-SUV",
    transmission: "Tự động",
    year: 2025,
    description: "Xe SUV cỡ nhỏ, cân bằng giữa phong cách và tiện nghi.",
  },
  {
    car_id: 4,
    name: "VinFast VF 5",
    brand: "VinFast",
    image_url:
      "/image/car/vf5.jpg",
    price_per_day: 980000,
    status: "available",
    color: "White",
    seats: 5,
    fuel_type: "Electric",
    transmission: "Tự động",
    year: 2025,
    description: "Gọn gàng, tiết kiệm, phù hợp di chuyển nội đô và đi gần.",
  },
  {
    car_id: 5,
    name: "VinFast Lux A2.0",
    brand: "VinFast",
    image_url:
      "/image/car/luxA2.0.jpg",
    price_per_day: 1400000,
    status: "available",
    color: "Black",
    seats: 5,
    fuel_type: "Sedan",
    transmission: "Tự động",
    year: 2024,
    description: "Sedan sang trọng, phù hợp chạy đường dài và gia đình.",
  },
  {
    car_id: 6,
    name: "VinFast Lux SA2.0",
    brand: "VinFast",
    image_url:
      "/image/car/luxSA2.0.jpg",
    price_per_day: 1600000,
    status: "available",
    color: "Silver",
    seats: 7,
    fuel_type: "SUV",
    transmission: "Tự động",
    year: 2024,
    description: "SUV 7 chỗ rộng rãi, phù hợp đi nhóm và gia đình.",
  },
  {
    car_id: 7,
    name: "Tesla Model 3",
    brand: "Tesla",
    image_url:
      "/image/car/teslamodel3.jpg",
    price_per_day: 2200000,
    status: "available",
    color: "Red",
    seats: 5,
    fuel_type: "Electric",
    transmission: "Tự động",
    year: 2025,
    description: "Xe điện hiệu suất cao, trải nghiệm công nghệ hiện đại.",
  },
  {
    car_id: 8,
    name: "Tesla Model Y",
    brand: "Tesla",
    image_url:
      "/image/car/teslamodely.avif",
    price_per_day: 2500000,
    status: "available",
    color: "Gray",
    seats: 5,
    fuel_type: "Electric",
    transmission: "Tự động",
    year: 2025,
    description: "Cốp rộng, gầm cao, phù hợp gia đình và du lịch.",
  },
  {
    car_id: 9,
    name: "Toyota Innova",
    brand: "Toyota",
    image_url:
      "/image/car/innova.webp",
    price_per_day: 950000,
    status: "available",
    color: "Silver",
    seats: 7,
    fuel_type: "Hybrid",
    transmission: "Tự động",
    year: 2024,
    description: "Xe gia đình đa dụng, thoải mái cho hành trình dài.",
  },
  {
    car_id: 10,
    name: "Toyota Vios",
    brand: "Toyota",
    image_url:
      "/image/car/vios.jpg",
    price_per_day: 650000,
    status: "available",
    color: "White",
    seats: 5,
    fuel_type: "Sedan",
    transmission: "Tự động",
    year: 2023,
    description: "Sedan phổ thông, bền bỉ, chi phí vận hành hợp lý.",
  },
  {
    car_id: 11,
    name: "Mazda CX-5",
    brand: "Mazda",
    image_url:
      "/image/car/cx5.webp",
    price_per_day: 1100000,
    status: "available",
    color: "Gray",
    seats: 5,
    fuel_type: "SUV",
    transmission: "Tự động",
    year: 2024,
    description: "SUV thể thao, cân bằng giữa tiện nghi và vận hành.",
  },
  {
    car_id: 12,
    name: "Mazda 3",
    brand: "Mazda",
    image_url:
      "/image/car/mazda3.webp",
    price_per_day: 820000,
    status: "available",
    color: "Blue",
    seats: 5,
    fuel_type: "Sedan",
    transmission: "Tự động",
    year: 2024,
    description: "Thiết kế đẹp, lái đầm, phù hợp đi làm và đi chơi.",
  },
  {
    car_id: 13,
    name: "Kia Seltos",
    brand: "Kia",
    image_url:
      "/image/car/seltos.webp",
    price_per_day: 900000,
    status: "available",
    color: "Orange",
    seats: 5,
    fuel_type: "SUV",
    transmission: "Tự động",
    year: 2024,
    description: "SUV đô thị, gọn nhưng rộng rãi, nhiều tiện ích.",
  },
  {
    car_id: 14,
    name: "Hyundai Accent",
    brand: "Hyundai",
    image_url:
      "/image/car/accent.webp",
    price_per_day: 620000,
    status: "available",
    color: "White",
    seats: 5,
    fuel_type: "Sedan",
    transmission: "Tự động",
    year: 2023,
    description: "Sedan tiết kiệm nhiên liệu, phù hợp mọi nhu cầu di chuyển.",
  },
  {
    car_id: 15,
    name: "Hyundai SantaFe",
    brand: "Hyundai",
    image_url:
      "/image/car/santafe.jpg",
    price_per_day: 1350000,
    status: "available",
    color: "Black",
    seats: 7,
    fuel_type: "SUV",
    transmission: "Tự động",
    year: 2024,
    description: "7 chỗ rộng rãi, phù hợp gia đình, đi tỉnh, du lịch.",
  },
];

